spring:
  application:
    name: eureka-server
    
server:
  port: 8761
  
eureka:
  client:
    regiseterWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 30    
  serviceUrl:
    defaultZone: http://localhost:8761